package org.ops4j.pax.cdi.openwebbeans.impl;

import org.osgi.framework.Bundle;
import org.osgi.framework.hooks.weaving.WeavingHook;
import org.osgi.framework.hooks.weaving.WovenClass;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A weaving hook which adds a dynamic package import for {@code javassist.util.proxy} for
 * all classes from beans bundles. This is required for Javassist proxies for managed beans
 * generated by OpenWebBeans.
 * 
 * @author Harald Wellmann
 */
public class ProxyWeavingHook implements WeavingHook {

	private static Logger log = LoggerFactory.getLogger(ProxyWeavingHook.class);

	@Override
	public void weave(WovenClass wovenClass) {
		Bundle bundle = wovenClass.getBundleWiring().getBundle();
		if (bundle.getHeaders().get("Pax-ManagedBeans") != null) {		
			log.debug("weaving {}", wovenClass.getClassName());
			wovenClass.getDynamicImports().add("javassist.util.proxy");
		}
	}
}
